rule report:
    input:
        annotation=sample_report_files(),
        abundance="results/cohort/abundance/plasmid_abundance.tsv",
        differential="results/cohort/differential/differential_plasmids.tsv",
        alpha="results/cohort/diversity/alpha_diversity.tsv",
        beta="results/cohort/diversity/beta_distance_matrix.tsv",
        network="results/cohort/network/network_edges.tsv"
    output:
        html="report/report.html",
        pdf="report/report.pdf"
    shell:
        """
        mkdir -p report/figures
        cat > {output.html} << 'HTML'
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Plasmid Pipeline Report</title></head>
<body>
<h1>Metagenomic Plasmid Pipeline Report</h1>
<p>MVP scaffold report generated by Snakemake.</p>
</body>
</html>
HTML
        printf "Mock PDF placeholder\n" > {output.pdf}
        printf "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='80'><text x='10' y='40'>Mock SVG Figure</text></svg>\n" > report/figures/overview.svg
        """
